export const _log = console.log.bind('[Session player]')
export const _warn = console.warn.bind('[Session player]')
export const _info = console.info.bind('[Session player]')
export const _debug = console.debug.bind('[Session player]')
export const _error = console.error.bind('[Session player]')